#!/bin/bash
# Version 6 - Plasma 6

# This script detects if the widget is already installed.
# If it is, it will use --upgrade instead and restart plasmashell.

# Read plugin ID from metadata.json
packageNamespace=$(grep -oP '"Id"\s*:\s*"\K[^"]+' "$PWD/package/metadata.json" 2>/dev/null)
if [ -z "$packageNamespace" ]; then
	echo "Error: Could not read Id from package/metadata.json"
	exit 1
fi

packageServiceType="Plasma/Applet"
restartPlasmashell=false

for arg in "$@"; do
	case "$arg" in
		-r) restartPlasmashell=true;;
		--restart) restartPlasmashell=true;;
		*) ;;
	esac
done

isAlreadyInstalled=false
kpackagetool6 --type="${packageServiceType}" --show="$packageNamespace" &> /dev/null
if [ $? == 0 ]; then
	isAlreadyInstalled=true
fi

if $isAlreadyInstalled; then
	# Eg: kpackagetool6 -t "Plasma/Applet" -u package
	kpackagetool6 -t "${packageServiceType}" -u package
	restartPlasmashell=true
else
	# Eg: kpackagetool6 -t "Plasma/Applet" -i package
	kpackagetool6 -t "${packageServiceType}" -i package
fi

if $restartPlasmashell; then
	# For Plasma 6, use systemctl to restart plasmashell
	if command -v systemctl &> /dev/null && systemctl --user is-active plasma-plasmashell.service &> /dev/null; then
		systemctl --user restart plasma-plasmashell.service
	else
		killall plasmashell
		kstart plasmashell &
	fi
fi
