#!/bin/sh
# Version: 8

# This script will convert the *.po files to *.mo files, rebuilding the package/contents/locale folder.
# Feature discussion: https://phabricator.kde.org/D5209
# Eg: contents/locale/fr_CA/LC_MESSAGES/plasma_applet_org.kde.plasma.eventcalendar.mo

DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
metadataFile="$DIR/../metadata.desktop"
readMetadataValue() {
	key="$1"
	sed -n 's/^'"${key}"'=//p' "$metadataFile" | head -n 1
}
plasmoidName=$(readMetadataValue "X-KDE-PluginInfo-Name")
website=$(readMetadataValue "X-KDE-PluginInfo-Website")
bugAddress="$website"
packageRoot="${DIR}/.." # Root of translatable sources
projectName="plasma_applet_${plasmoidName}" # project name

### Colors
# https://stackoverflow.com/questions/5947742/how-to-change-the-output-color-of-echo-in-linux
# https://stackoverflow.com/questions/911168/how-can-i-detect-if-my-shell-script-is-running-through-a-pipe
TC_Red='\033[31m'; TC_Orange='\033[33m';
TC_LightGray='\033[90m'; TC_LightRed='\033[91m'; TC_LightGreen='\033[92m'; TC_Yellow='\033[93m'; TC_LightBlue='\033[94m';
TC_Reset='\033[0m'; TC_Bold='\033[1m';
if [ ! -t 1 ]; then
	TC_Red=''; TC_Orange='';
	TC_LightGray=''; TC_LightRed=''; TC_LightGreen=''; TC_Yellow=''; TC_LightBlue='';
	TC_Bold=''; TC_Reset='';
fi
echoTC() {
	text="$1"
	textColor="$2"
	printf '%b\n' "${textColor}${text}${TC_Reset}"
}
echoGray() { echoTC "$1" "$TC_LightGray"; }
echoRed() { echoTC "$1" "$TC_Red"; }
echoGreen() { echoTC "$1" "$TC_LightGreen"; }

#---
if [ -z "$plasmoidName" ]; then
	echoRed "[translate/build] Error: Couldn't read plasmoidName."
	exit 1
fi

if ! command -v msgfmt >/dev/null 2>&1; then
	echoRed "[translate/build] Error: msgfmt command not found. Need to install gettext"
	exit 1
fi

#---
echoGray "[translate/build] Compiling messages"

catalogs=$(find "$DIR" -maxdepth 1 -name '*.po' | sort)
for cat in $catalogs; do
	catLocale=$(basename "${cat%.*}")
	relativeInstallPath="contents/locale/${catLocale}/LC_MESSAGES/${projectName}.mo"
	installPath="${packageRoot}/${relativeInstallPath}"
	echoGray "[translate/build] Converting '${cat}' => '${relativeInstallPath}'"
	mkdir -p "$(dirname "$installPath")"
	msgfmt -o "${installPath}" "${cat}" || exit 1
done

echoGreen "[translate/build] Done building messages"

if [ "$1" = "--restartplasma" ]; then
	echo "[translate/build] ${TC_Bold}Restarting plasmashell${TC_Reset}"
	systemctl --user restart plasma-plasmashell.service
	echo "[translate/build] Done restarting plasmashell"
else
	echo "[translate/build] (re)install the plasmoid and restart plasmashell to test translations."
fi
